package com.componentes.landyard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;


@DynamoDBTable(tableName = "Evento")
@Data
public class Evento {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private  String id;

    @DynamoDBAttribute(attributeName = "Descripcion")
    private  String Descripcion;

    @DynamoDBAttribute(attributeName = "Fecha")
    private  String Fecha ;

    @DynamoDBAttribute(attributeName = "Imagen")
    private  String Imagen ;

    @DynamoDBAttribute(attributeName = "Lugar")
    private  String Lugar ;

    @DynamoDBAttribute(attributeName = "NombreEvento")
    private  String NombreEvento ;

    @DynamoDBAttribute(attributeName = "Productora")
    private  String Productora ;

    @DynamoDBAttribute(attributeName = "Tipo")
    private  String Tipo ;
}
